import type { Creator, HashtagPost, Script, ScriptHookOption, SignalRecord } from "./contracts";

export const demoCreators: Creator[] = [
  {
    id: "creator-field-notes",
    name: "Field Notes Studio",
    handle: "@fieldnotesstudio",
    network: "youtube",
    audience: 84200,
    accent: "#ff6546",
  },
  {
    id: "creator-practical-futures",
    name: "Practical Futures",
    handle: "@practicalfutures",
    network: "youtube",
    audience: 137000,
    accent: "#2c6e62",
  },
  {
    id: "creator-studio-index",
    name: "Studio Index",
    handle: "@studioindex",
    network: "instagram",
    audience: 56900,
    accent: "#59645f",
  },
  {
    id: "creator-useful-machines",
    name: "Useful Machines",
    handle: "@usefulmachines",
    network: "tiktok",
    audience: 211000,
    accent: "#be533d",
  },
];

export const demoSignals: SignalRecord[] = [
  {
    id: "signal-briefs",
    creatorId: "creator-field-notes",
    title: "The five-minute brief that stops revision loops",
    publishedAt: "2026-08-22T09:20:00.000Z",
    views: 184000,
    likes: 12900,
    comments: 884,
    durationSeconds: 522,
    thumbnailSeed: "brief-workshop",
    topic: "creative operations",
  },
  {
    id: "signal-agents",
    creatorId: "creator-practical-futures",
    title: "I gave one agent a real operating budget",
    publishedAt: "2026-08-21T22:00:00.000Z",
    views: 426000,
    likes: 31800,
    comments: 1430,
    durationSeconds: 688,
    thumbnailSeed: "agent-budget",
    topic: "agent workflows",
  },
  {
    id: "signal-thumbnail",
    creatorId: "creator-studio-index",
    title: "Why quiet thumbnails are winning again",
    publishedAt: "2026-08-19T18:45:00.000Z",
    views: 91600,
    likes: 8500,
    comments: 506,
    durationSeconds: 74,
    thumbnailSeed: "quiet-thumbnail",
    topic: "packaging",
    format: "reel",
    url: "https://www.instagram.com/reel/demo-quiet-thumbnail/",
    caption: "Warum ruhige Thumbnails wieder funktionieren.",
    transcript: "Laute Gestalltung gewinnt nicht automatisch Aufmerksammkeit. Manchmal macht ein ruhiges Thumnail den Inhalt glaubwürdiger.",
    transcriptSegments: [
      { start: 0, end: 3.8, text: "Laute Gestalltung gewinnt nicht automatisch Aufmerksammkeit." },
      { start: 3.8, end: 8.6, text: "Manchmal macht ein ruhiges Thumnail den Inhalt glaubwürdiger." },
    ],
    transcriptWorkingCopy: "Laute Gestaltung gewinnt nicht automatisch Aufmerksammkeit. Manchmal macht ein ruhiges Thumbnail den Inhalt glaubwürdiger.",
    transcriptCorrections: [
      {
        id: "demo-correction-gestaltung",
        original: "Gestalltung",
        replacement: "Gestaltung",
        reason: "Offensichtlicher Erkennungsfehler.",
        source: "bridge",
        status: "accepted",
        createdAt: "2026-08-21T08:30:00.000Z",
      },
      {
        id: "demo-correction-thumbnail",
        original: "Thumnail",
        replacement: "Thumbnail",
        reason: "Produktbegriff wirkt falsch erkannt.",
        source: "bridge",
        status: "accepted",
        createdAt: "2026-08-21T08:30:00.000Z",
      },
      {
        id: "demo-correction-attention",
        original: "Aufmerksammkeit",
        replacement: "Aufmerksamkeit",
        reason: "Einzelwort wirkt falsch erkannt.",
        source: "bridge",
        status: "proposed",
        createdAt: "2026-08-21T08:30:00.000Z",
      },
    ],
    transcriptAttempts: 1,
    transcriptUpdatedAt: "2026-08-21T08:30:00.000Z",
    transcriptStatus: "ready",
  },
  {
    id: "signal-memory",
    creatorId: "creator-useful-machines",
    title: "A memory layer you can inspect with plain text",
    publishedAt: "2026-08-18T09:15:00.000Z",
    views: 792000,
    likes: 66700,
    comments: 2204,
    durationSeconds: 141,
    thumbnailSeed: "plain-text-memory",
    topic: "agent workflows",
  },
  {
    id: "signal-manual-transcript",
    creatorId: "creator-studio-index",
    title: "The small change that makes a Reel easier to trust",
    publishedAt: "2026-08-17T13:10:00.000Z",
    views: 64800,
    likes: 6100,
    comments: 318,
    durationSeconds: 46,
    thumbnailSeed: "manual-transcript",
    topic: "packaging",
    format: "reel",
    url: "https://www.instagram.com/reel/demo-manual-transcript/",
    caption: "Ein kleines Detail macht einen Reel sofort glaubwürdiger.",
  },
  {
    id: "signal-format",
    creatorId: "creator-field-notes",
    title: "The teardown format that earns saves",
    publishedAt: "2026-08-16T16:30:00.000Z",
    views: 103000,
    likes: 9800,
    comments: 611,
    durationSeconds: 417,
    thumbnailSeed: "format-teardown",
    topic: "content formats",
  },
  {
    id: "signal-research",
    creatorId: "creator-practical-futures",
    title: "Research systems should show their receipts",
    publishedAt: "2026-08-14T11:05:00.000Z",
    views: 171000,
    likes: 11400,
    comments: 730,
    durationSeconds: 603,
    thumbnailSeed: "research-receipts",
    topic: "evidence systems",
  },
];

/** Synthetic Trend-Radar corpus used only while the real store is empty. */
export const demoHashtagPosts: HashtagPost[] = [
  {
    id: "ig-hashtag-demo-agent-1",
    externalId: "demo-agent-1",
    hashtag: "kiagenten",
    hashtags: ["kiagenten", "claude"],
    ownerHandle: "@demo-lab",
    title: "So arbeiten KI-Agenten mit echtem Budget",
    caption: "So arbeiten KI-Agenten mit echtem Budget und weniger manueller Arbeit.",
    publishedAt: "2026-08-22T11:00:00.000Z",
    plays: 220000,
    likes: 12000,
    comments: 420,
    url: "https://www.instagram.com/p/demo-agent-1/",
    topic: "ki-agenten",
    language: "de",
    collectedAt: "2026-08-22T16:00:00.000Z",
  },
  {
    id: "ig-hashtag-demo-agent-2",
    externalId: "demo-agent-2",
    hashtag: "kiagenten",
    hashtags: ["kiagenten"],
    ownerHandle: "@demo-werkstatt",
    title: "Wie du KI-Agenten sicher testest",
    caption: "Wie du KI-Agenten sicher testest, bevor sie Aufgaben übernehmen.",
    publishedAt: "2026-08-20T12:00:00.000Z",
    plays: 180000,
    likes: 9000,
    comments: 280,
    url: "https://www.instagram.com/p/demo-agent-2/",
    topic: "ki-agenten",
    language: "de",
    collectedAt: "2026-08-22T16:00:00.000Z",
  },
  {
    id: "ig-hashtag-demo-agent-old",
    externalId: "demo-agent-old",
    hashtag: "kiagenten",
    hashtags: ["kiagenten"],
    ownerHandle: "@demo-lab",
    title: "Ein KI-Agent für die Recherche",
    caption: "Ein KI-Agent hilft dir bei der Recherche mit klaren Quellen.",
    publishedAt: "2026-08-13T12:00:00.000Z",
    plays: 60000,
    likes: 3000,
    comments: 110,
    url: "https://www.instagram.com/p/demo-agent-old/",
    topic: "ki-agenten",
    language: "de",
    collectedAt: "2026-08-22T16:00:00.000Z",
  },
  {
    id: "ig-hashtag-demo-vibe-1",
    externalId: "demo-vibe-1",
    hashtag: "vibecoding",
    hashtags: ["vibecoding"],
    ownerHandle: "@demo-code",
    title: "Vibe Coding für den ersten Prototyp",
    caption: "Vibe Coding macht aus einer Idee in einer Stunde einen Prototyp.",
    publishedAt: "2026-08-21T10:00:00.000Z",
    plays: 130000,
    likes: 7000,
    comments: 210,
    url: "https://www.instagram.com/p/demo-vibe-1/",
    topic: "vibe-coding",
    language: "de",
    collectedAt: "2026-08-22T16:00:00.000Z",
  },
  {
    id: "ig-hashtag-demo-vibe-old",
    externalId: "demo-vibe-old",
    hashtag: "vibecoding",
    hashtags: ["vibecoding"],
    ownerHandle: "@demo-code",
    title: "Mit Cursor schneller bauen",
    caption: "Mit Cursor kannst du schneller bauen und deine Idee prüfen.",
    publishedAt: "2026-08-12T10:00:00.000Z",
    plays: 100000,
    likes: 5000,
    comments: 180,
    url: "https://www.instagram.com/p/demo-vibe-old/",
    topic: "vibe-coding",
    language: "de",
    collectedAt: "2026-08-22T16:00:00.000Z",
  },
];

/** Synthetic Script projects shown only while the store is empty. */
export const demoScriptIdeaTitles: Record<string, string> = {
  "idea-script-hook": "The first line is the production decision",
  "idea-script-draft": "A quieter way to explain an agent workflow",
  "idea-script-review": "What visible proof does for trust",
  "idea-script-approved": "The five-minute brief that stops revision loops",
};

export const demoScripts: Script[] = [
  {
    id: "script-demo-hook-selection",
    ideaId: "idea-script-hook",
    sourceSignalId: "signal-thumbnail",
    evidenceSignalIds: ["signal-thumbnail", "signal-manual-transcript"],
    status: "hook-selection",
    framework: "pas",
    frameworkReason: "The tension is clearest when the cost of the old workflow comes first.",
    hookOptions: [
      {
        id: "demo-hook-option-1",
        hook: "Die lauteste erste Zeile ist selten die glaubwürdigste.",
        angle: "Show why restraint can make a useful idea easier to trust.",
        hypothesis: "A small contradiction earns attention before the explanation starts.",
        framework: "pas",
        evidence: [{ signalId: "signal-thumbnail", hook: "Laute Gestaltung gewinnt nicht automatisch Aufmerksamkeit.", creator: "@studioindex", outlier: 1.61, fit: "The source Reel turns a quiet visual choice into a trust argument." }],
        edited: false,
      },
      {
        id: "demo-hook-option-2",
        hook: "Was, wenn weniger Reiz mehr Klarheit schafft?",
        angle: "Use a question to make the viewer test the assumption on their own feed.",
        hypothesis: "An open question creates a gap the proof can close.",
        framework: "bbb",
        evidence: [{ signalId: "signal-manual-transcript", hook: "Ein kleines Detail macht einen Reel sofort glaubwürdiger.", creator: "@studioindex", outlier: 1.14, fit: "The adjacent Reel supports a detail-first explanation." }],
        edited: false,
      },
    ],
    sections: [],
    revision: 0,
    createdAt: "2026-08-30T09:00:00.000Z",
    updatedAt: "2026-08-31T09:15:00.000Z",
  },
  {
    id: "script-demo-draft",
    ideaId: "idea-script-draft",
    sourceSignalId: "signal-manual-transcript",
    evidenceSignalIds: ["signal-manual-transcript", "signal-agents"],
    status: "draft",
    framework: "bbb",
    frameworkReason: "The idea needs a concrete example before the broader claim.",
    hookOptions: [],
    selectedHookId: "demo-hook-draft",
    sections: [
      { kind: "hook", label: "Hook", text: "Ein Agent wird erst nützlich, wenn du seinen Arbeitsweg sehen kannst." },
      { kind: "beat", label: "Das Problem", text: "Viele Workflows zeigen nur das Ergebnis und verstecken die Entscheidungen dazwischen." },
      { kind: "beat", label: "Der Beleg", text: "Zeige einen kleinen Auftrag mit Input, Zwischenstand und einer klaren Abbruchregel." },
      { kind: "cta", label: "CTA", text: "Speichere dir die drei Stationen für deinen nächsten Test." },
    ],
    revision: 1,
    createdAt: "2026-08-27T10:00:00.000Z",
    updatedAt: "2026-08-30T14:20:00.000Z",
  },
  {
    id: "script-demo-review",
    ideaId: "idea-script-review",
    sourceSignalId: "signal-thumbnail",
    evidenceSignalIds: ["signal-thumbnail", "signal-research"],
    status: "review",
    framework: "pas",
    frameworkReason: "Start with the trust problem, then make the visible receipt the relief.",
    hookOptions: [],
    selectedHookId: "demo-hook-review",
    sections: [
      { kind: "hook", label: "Hook", text: "Vertrauen entsteht nicht durch eine größere Behauptung." },
      { kind: "beat", label: "Problem", text: "Wenn der Weg zur Aussage unsichtbar bleibt, muss das Publikum dem Ergebnis blind glauben." },
      { kind: "transition", label: "Wendung", text: "Ein einziger sichtbarer Beleg verändert diese Prüfung." },
      { kind: "beat", label: "Beleg", text: "Zeige die Quelle, die Entscheidung und die Stelle, an der du bewusst nicht weitergehst." },
      { kind: "beat", label: "Konsequenz", text: "So wird aus einer starken Aussage ein nachvollziehbarer Arbeitsweg." },
      { kind: "cta", label: "CTA", text: "Prüfe deinen nächsten Beitrag auf genau einen sichtbaren Beleg." },
    ],
    revision: 2,
    createdAt: "2026-08-25T08:30:00.000Z",
    updatedAt: "2026-08-29T16:45:00.000Z",
  },
  {
    id: "script-demo-approved",
    ideaId: "idea-script-approved",
    sourceSignalId: "signal-thumbnail",
    evidenceSignalIds: ["signal-briefs", "signal-format"],
    status: "approved",
    framework: "none",
    frameworkReason: "The sequence is simple enough to carry without a named framework.",
    hookOptions: [],
    selectedHookId: "demo-hook-approved",
    sections: [
      { kind: "hook", label: "Hook", text: "Ein gutes Briefing beendet die Revision, bevor sie beginnt." },
      { kind: "beat", label: "Der Engpass", text: "Die meisten Briefings sammeln Material, aber treffen keine Entscheidung." },
      { kind: "beat", label: "Die Regel", text: "Lege zuerst fest, was nach fünf Minuten klar sein muss." },
      { kind: "beat", label: "Das Beispiel", text: "Zeige danach nur die drei Belege, die diese Entscheidung tragen." },
      { kind: "cta", label: "CTA", text: "Teste die Regel beim nächsten Briefing und streiche alles, was keine Entscheidung stützt." },
    ],
    revision: 1,
    approvedRevision: 1,
    approvedAt: "2026-08-28T11:10:00.000Z",
    createdAt: "2026-08-22T09:00:00.000Z",
    updatedAt: "2026-08-28T11:10:00.000Z",
  },
];

/** Fixed Lektorat suggestions shown for matching demo sections; nothing is auto-applied. */
export const demoScriptLintSuggestions = [
  {
    sectionId: "section-2",
    original: "Viele Workflows zeigen nur das Ergebnis und verstecken die Entscheidungen dazwischen.",
    replacement: "Viele Workflows zeigen nur das Ergebnis. Die Entscheidungen dazwischen bleiben unsichtbar.",
    reason: "Zwei konkrete Sätze lesen sich hier klarer als eine aufgeladene Gegensatzkonstruktion.",
  },
  {
    sectionId: "section-2",
    original: "Wenn der Weg zur Aussage unsichtbar bleibt, muss das Publikum dem Ergebnis blind glauben.",
    replacement: "Wenn der Weg zur Aussage unsichtbar bleibt, glaubt das Publikum dem Ergebnis blind.",
    reason: "Die Aussage kommt ohne die unnötige Modalform direkter auf den Punkt.",
  },
];

/** Fixed Hook options used when an empty store develops a captured Idea without a Bridge. */
export const demoScriptHookOptions: ScriptHookOption[] = [
  {
    id: "demo-develop-hook-1",
    hook: "Die erste Zeile entscheidet, ob der Beleg überhaupt eine Chance bekommt.",
    angle: "Beginne mit dem Engpass zwischen einer starken Beobachtung und ihrer sichtbaren Erklärung.",
    hypothesis: "Ein konkreter Widerspruch öffnet Spannung, bevor die Erklärung beginnt.",
    framework: "pas",
    evidence: [],
    edited: false,
  },
  {
    id: "demo-develop-hook-2",
    hook: "Was würde sich ändern, wenn du den Beleg vor die Behauptung stellst?",
    angle: "Lass das Publikum die Reihenfolge an einem kleinen Beispiel selbst prüfen.",
    hypothesis: "Eine offene Frage hält die Aufmerksamkeit bis zum sichtbaren Beleg.",
    framework: "bbb",
    evidence: [],
    edited: false,
  },
  {
    id: "demo-develop-hook-3",
    hook: "Die ruhigste Erklärung kann die stärkste Reaktion auslösen.",
    angle: "Zeige, wie eine klare Szene eine laute Behauptung ersetzt.",
    hypothesis: "Eine unerwartete Zuspitzung macht das Thema merkbar, ohne es aufzublasen.",
    framework: "none",
    evidence: [],
    edited: false,
  },
];

export const demoIdeas = [
  {
    id: "idea-1",
    title: "The agent workflow nobody documents",
    format: "Evidence-led teardown",
    evidence: 3,
    state: "Ready to brief",
  },
  {
    id: "idea-2",
    title: "Why visible receipts build AI trust",
    format: "Contrarian explainer",
    evidence: 2,
    state: "Needs one example",
  },
  {
    id: "idea-3",
    title: "The small-team operating system",
    format: "Field guide",
    evidence: 4,
    state: "Drafting",
  },
];
