import type { Creator, HashtagPost, SignalRecord } from "./contracts";

export const demoCreators: Creator[] = [
  {
    id: "creator-field-notes",
    name: "Field Notes Studio",
    handle: "@fieldnotesstudio",
    network: "youtube",
    audience: 84200,
    accent: "#ff6546",
  },
  {
    id: "creator-practical-futures",
    name: "Practical Futures",
    handle: "@practicalfutures",
    network: "youtube",
    audience: 137000,
    accent: "#2c6e62",
  },
  {
    id: "creator-studio-index",
    name: "Studio Index",
    handle: "@studioindex",
    network: "instagram",
    audience: 56900,
    accent: "#59645f",
  },
  {
    id: "creator-useful-machines",
    name: "Useful Machines",
    handle: "@usefulmachines",
    network: "tiktok",
    audience: 211000,
    accent: "#be533d",
  },
];

export const demoSignals: SignalRecord[] = [
  {
    id: "signal-briefs",
    creatorId: "creator-field-notes",
    title: "The five-minute brief that stops revision loops",
    publishedAt: "2026-08-22T09:20:00.000Z",
    views: 184000,
    likes: 12900,
    comments: 884,
    durationSeconds: 522,
    thumbnailSeed: "brief-workshop",
    topic: "creative operations",
  },
  {
    id: "signal-agents",
    creatorId: "creator-practical-futures",
    title: "I gave one agent a real operating budget",
    publishedAt: "2026-08-21T22:00:00.000Z",
    views: 426000,
    likes: 31800,
    comments: 1430,
    durationSeconds: 688,
    thumbnailSeed: "agent-budget",
    topic: "agent workflows",
  },
  {
    id: "signal-thumbnail",
    creatorId: "creator-studio-index",
    title: "Why quiet thumbnails are winning again",
    publishedAt: "2026-08-19T18:45:00.000Z",
    views: 91600,
    likes: 8500,
    comments: 506,
    durationSeconds: 74,
    thumbnailSeed: "quiet-thumbnail",
    topic: "packaging",
    format: "reel",
    url: "https://www.instagram.com/reel/demo-quiet-thumbnail/",
    caption: "Warum ruhige Thumbnails wieder funktionieren.",
    transcript: "Laute Gestaltung gewinnt nicht automatisch Aufmerksamkeit. Manchmal macht ein ruhiges Thumbnail den Inhalt glaubwürdiger.",
    transcriptSegments: [
      { start: 0, end: 3.8, text: "Laute Gestaltung gewinnt nicht automatisch Aufmerksamkeit." },
      { start: 3.8, end: 8.6, text: "Manchmal macht ein ruhiges Thumbnail den Inhalt glaubwürdiger." },
    ],
    transcriptAttempts: 1,
    transcriptUpdatedAt: "2026-08-21T08:30:00.000Z",
    transcriptStatus: "ready",
  },
  {
    id: "signal-memory",
    creatorId: "creator-useful-machines",
    title: "A memory layer you can inspect with plain text",
    publishedAt: "2026-08-18T09:15:00.000Z",
    views: 792000,
    likes: 66700,
    comments: 2204,
    durationSeconds: 141,
    thumbnailSeed: "plain-text-memory",
    topic: "agent workflows",
  },
  {
    id: "signal-format",
    creatorId: "creator-field-notes",
    title: "The teardown format that earns saves",
    publishedAt: "2026-08-16T16:30:00.000Z",
    views: 103000,
    likes: 9800,
    comments: 611,
    durationSeconds: 417,
    thumbnailSeed: "format-teardown",
    topic: "content formats",
  },
  {
    id: "signal-research",
    creatorId: "creator-practical-futures",
    title: "Research systems should show their receipts",
    publishedAt: "2026-08-14T11:05:00.000Z",
    views: 171000,
    likes: 11400,
    comments: 730,
    durationSeconds: 603,
    thumbnailSeed: "research-receipts",
    topic: "evidence systems",
  },
];

/** Synthetic Trend-Radar corpus used only while the real store is empty. */
export const demoHashtagPosts: HashtagPost[] = [
  {
    id: "ig-hashtag-demo-agent-1",
    externalId: "demo-agent-1",
    hashtag: "kiagenten",
    hashtags: ["kiagenten", "claude"],
    ownerHandle: "@demo-lab",
    title: "So arbeiten KI-Agenten mit echtem Budget",
    caption: "So arbeiten KI-Agenten mit echtem Budget und weniger manueller Arbeit.",
    publishedAt: "2026-08-22T11:00:00.000Z",
    plays: 220000,
    likes: 12000,
    comments: 420,
    url: "https://www.instagram.com/p/demo-agent-1/",
    topic: "ki-agenten",
    language: "de",
    collectedAt: "2026-08-22T16:00:00.000Z",
  },
  {
    id: "ig-hashtag-demo-agent-2",
    externalId: "demo-agent-2",
    hashtag: "kiagenten",
    hashtags: ["kiagenten"],
    ownerHandle: "@demo-werkstatt",
    title: "Wie du KI-Agenten sicher testest",
    caption: "Wie du KI-Agenten sicher testest, bevor sie Aufgaben übernehmen.",
    publishedAt: "2026-08-20T12:00:00.000Z",
    plays: 180000,
    likes: 9000,
    comments: 280,
    url: "https://www.instagram.com/p/demo-agent-2/",
    topic: "ki-agenten",
    language: "de",
    collectedAt: "2026-08-22T16:00:00.000Z",
  },
  {
    id: "ig-hashtag-demo-agent-old",
    externalId: "demo-agent-old",
    hashtag: "kiagenten",
    hashtags: ["kiagenten"],
    ownerHandle: "@demo-lab",
    title: "Ein KI-Agent für die Recherche",
    caption: "Ein KI-Agent hilft dir bei der Recherche mit klaren Quellen.",
    publishedAt: "2026-08-13T12:00:00.000Z",
    plays: 60000,
    likes: 3000,
    comments: 110,
    url: "https://www.instagram.com/p/demo-agent-old/",
    topic: "ki-agenten",
    language: "de",
    collectedAt: "2026-08-22T16:00:00.000Z",
  },
  {
    id: "ig-hashtag-demo-vibe-1",
    externalId: "demo-vibe-1",
    hashtag: "vibecoding",
    hashtags: ["vibecoding"],
    ownerHandle: "@demo-code",
    title: "Vibe Coding für den ersten Prototyp",
    caption: "Vibe Coding macht aus einer Idee in einer Stunde einen Prototyp.",
    publishedAt: "2026-08-21T10:00:00.000Z",
    plays: 130000,
    likes: 7000,
    comments: 210,
    url: "https://www.instagram.com/p/demo-vibe-1/",
    topic: "vibe-coding",
    language: "de",
    collectedAt: "2026-08-22T16:00:00.000Z",
  },
  {
    id: "ig-hashtag-demo-vibe-old",
    externalId: "demo-vibe-old",
    hashtag: "vibecoding",
    hashtags: ["vibecoding"],
    ownerHandle: "@demo-code",
    title: "Mit Cursor schneller bauen",
    caption: "Mit Cursor kannst du schneller bauen und deine Idee prüfen.",
    publishedAt: "2026-08-12T10:00:00.000Z",
    plays: 100000,
    likes: 5000,
    comments: 180,
    url: "https://www.instagram.com/p/demo-vibe-old/",
    topic: "vibe-coding",
    language: "de",
    collectedAt: "2026-08-22T16:00:00.000Z",
  },
];

export const demoIdeas = [
  {
    id: "idea-1",
    title: "The agent workflow nobody documents",
    format: "Evidence-led teardown",
    evidence: 3,
    state: "Ready to brief",
  },
  {
    id: "idea-2",
    title: "Why visible receipts build AI trust",
    format: "Contrarian explainer",
    evidence: 2,
    state: "Needs one example",
  },
  {
    id: "idea-3",
    title: "The small-team operating system",
    format: "Field guide",
    evidence: 4,
    state: "Drafting",
  },
];
